/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {

    public static void printNumberOfTables(Connection conn){

    }
    public static void readAndPrintHotels(Connection conn){
        
    }

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        // TODO: Establish a connection (You will have to update url every time workspace resets)
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:8083/hotels","crio-learner","learner-crio");

        try{
        // TODO: Implement a method to Print the number of Tables in database `hotels`
        printNumberOfTables(conn);

        // TODO: Implement a method to Read and Print the Columns `hotel_name` and `star_rating` from table hotel_details
        readAndPrintHotels(conn);
        }
        catch(Exception e){
            System.out.println("Exception occured!!! \n "+ e.getStackTrace().toString());
        }
        finally{
            conn.close();
        }
    }
}
